version: "3.7"

services:
  nginx:
    container_name: nginx
    build:
      context: ./.docker/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./logs/nginx:/var/log/nginx/
    networks:
      connector_net:
        ipv4_address: 192.168.1.2

  php:
    container_name: php
    build:
      context: ./.docker/php
      args:
        TIMEZONE: Europe/Madrid
    restart: unless-stopped
    depends_on:
      - db
      - sql-server
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      # - XDEBUG_MODE=debug
      # - XDEBUG_CONFIG=client_host=host.docker.internal client_port=5902
    volumes:
      - ./:/var/www
    networks:
      connector_net:
        ipv4_address: 192.168.1.3

  db:
    build:
      context: ./.docker/mysql
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    restart: unless-stopped
    ports:
      - "${MYSQL_EXPOSED_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./data:/var/lib/mysql
      - ./.docker/mysql/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    networks:
      connector_net:
        ipv4_address: 192.168.1.4

  dbtest:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conector
      MYSQL_USER: antonio
      MYSQL_PASSWORD: antonio123
    volumes:
      - ./conector-data:/var/lib/mysql
      - ./.docker/conector-db/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    ports:
      - 3309:3306
    networks:
      connector_net:
        ipv4_address: 192.168.1.6

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    volumes:
      - eurowinserverdata:/var/opt/mssql
    ports:
      - "${SQL_SERVER_EXPOSED_PORT}:1433"
    networks:
      connector_net:
        ipv4_address: 192.168.1.5

volumes:
  eurowinserverdata:

networks:
  connector_net:
    ipam:
      config:
        - subnet: 192.168.1.0/24
