version: "3.8"

services:
  nginx:
    container_name: nginx
    build:
      context: ./.docker/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./logs/nginx:/var/log/nginx/
      - phpsocket:/var/run
    links:
      - php

  php:
    container_name: php
    build:
      context: ./.docker/php
      args:
        TIMEZONE: Europe/Madrid
    restart: unless-stopped
    depends_on:
      - bodecall-db
      - conector-db
      - eurowin-db
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
    volumes:
      - ./.docker/php/conector-pool-1.conf:/usr/local/etc/php-fpm.d/conector-pool-1.conf
      - ./:/var/www
      - phpsocket:/var/run
    links:
      - conector-db
      - bodecall-db
      - eurowin-db

  bodecall-db:
    container_name: bodecall-db
    build:
      context: ./.docker/bodecall-db
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${BODECALL_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${BODECALL_DB_DATABASE}
      - MYSQL_USER=${BODECALL_DB_USER}
      - MYSQL_PASSWORD=${BODECALL_DB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
      - ./.docker/bodecall-db/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    ports:
      - "${BODECALL_DB_EXPOSED_PORT}:${BODECALL_DB_PORT}"

  conector-db:
    container_name: conector-db
    build:
      context: ./.docker/conector-db
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${CONECTOR_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CONECTOR_DB_DATABASE}
      MYSQL_USER: ${CONECTOR_DB_USER}
      MYSQL_PASSWORD: ${CONECTOR_DB_PASSWORD}
      MYSQL_TCP_PORT: ${CONECTOR_DB_PORT}
    volumes:
      - ./conector-data:/var/lib/mysql
    ports:
      - "${CONECTOR_DB_EXPOSED_PORT}:${CONECTOR_DB_PORT}"

  eurowin-db:
    container_name: eurowin-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: ${EUROWIN_DB_PASSWORD}
      ACCEPT_EULA: ${EUROWIN_DB_ACCEPT_EULA}
    volumes:
      - eurowinserverdata:/var/opt/mssql
    ports:
      - "${EUROWIN_DB_EXPOSED_PORT}:${EUROWIN_DB_PORT}"

volumes:
  eurowinserverdata:
  phpsocket:
